pipeline 
{

    agent
    {
        node 
        {
            label 'qeff_node'
        }
    }
    stages 
    {
        stage('Install QEfficient')
        {
            steps
            {

                script
                {

                    def timestamp = sh(script: "date +%s", returnStdout: true).trim()
                    def container_name = ${BRANCH_NAME}_$(timestamp)

                    sh '''
                    . ~/.bashrc
                    docker run --privileged -dit --name ${container_name} -v ./:/efficient-transformers -v  ${HF_PATH}:${DOCKER_HF_PATH} ${DOCKER_LATEST}:master_latest
                    docker exec ${container_name} bash -c "
                    cd /efficient-transformers &&
                    export QEFF_HOME=$(pwd)
                    . /opt/qeff-env/bin/activate &&
                    pip install --upgrade pip setuptools &&
                    pip install .[test] &&
                    pip install junitparser pytest-xdist &&
                    rm -rf QEfficient "
                    '''
                }
            }
        }
        stage('Test')
        {
                steps
                {
                    //todo(ochougul): Increase when MQ tests are enabled 
		            timeout(time: 420, unit: 'MINUTES') 
                    {
                    sh '''
                    docker exec ${container_name} bash -c "
                    cd /efficient-transformers &&
                    . /opt/qeff-env/bin/activate &&
                    export TOKENIZERS_PARALLELISM=false &&
                    export PYTHONPATH=. &&
                    pytest tests --ignore tests/cloud --junitxml=tests/tests_log1.xml &&
                    pytest tests/cloud --junitxml=tests/tests_log2.xml &&
                    junitparser merge tests/tests_log1.xml tests/tests_log2.xml tests/tests_log.xml &&
                    deactivate &&
                    exit" 
                    '''
                }
            }
        }
    }
    post 
    {
         always 
         {
            script
            {
                try 
                {
                    sh '''
                    docker rm -f ${container_name}
                    sudo chown -R ubuntu .
                    '''
                } 
                catch (error) 
                {
                    echo "Failed to delete container ${container_name}: ${error}"
                }
            }
            
            junit 'tests/tests_log.xml'
            echo 'Cleaning Workspace'
            deleteDir()
         }
    }
       
}
