pipeline 
{

    agent{
        node 
        {
            label 'qeff_node'
        }
    }
    environment 
    {
        CONTAINER_NAME = "qeff_container"
    }
    stages 
    {
        stage('Check Changes') 
        {
            steps 
            {
                script 
                {
                    def changedFiles = sh(script: "git diff --name-only HEAD~1 HEAD", returnStdout: true).trim().split('\n')
                    if ('pyproject.toml' in changedFiles) 
                    {
                         echo "Change in pyproject.toml detected"
                         //build job: 'efficient_transformer_docker_build',  parameters: [string(name: 'BRANCH_NAME', value:  env.BRANCH_NAME.replace('PR-', ''), description: 'Branch name to checkout')]
                    }
                    else
                    {
                        echo " There is no chnage in pyproject.toml"
                       // echo "Change in pyproject.toml detected"
                        //build job: 'efficient_transformer_docker_build',  parameters: [string(name: 'BRANCH_NAME', value:  env.BRANCH_NAME.replace('PR-', ''), description: 'Branch name to checkout')]
                    }
                }
            }
        }
        stage('Install QEfficient')
        {
            steps
            {

                script
                {
                    sh '''
                    docker run --privileged -dit --name ${CONTAINER_NAME} -v ./:/data -v  ${huggingface_hub_path}:${docker_huggingface_hub_path} ${docker_latest}:master_latest
                    docker exec ${CONTAINER_NAME} bash -c "
                    cd /data
                    . /opt/qeff-env/bin/activate
                    pip install --upgrade pip setuptools &&
                    pip install .[test]"
                    '''
                }
            }
        }
        stage('Test')
        {
                steps
                {
                    //todo(ochougul): Increase when MQ tests are enabled 
		            timeout(time: 420, unit: 'MINUTES') 
                    {
                    sh '''
                    docker exec ${CONTAINER_NAME} bash -c "
                    cd /data &&
                    . /opt/qeff-env/bin/activate
                    export TOKENIZERS_PARALLELISM=false &&
                    deactivate &&
                    exit"
                    sudo chown -R ubuntu ./*
                    '''
                    
                }
            }
        }
    }
    post 
    {
         always 
         {
            script
            {
                try 
                {
                    sh '''
                    docker ps
                    docker rm -f ${CONTAINER_NAME}
                    '''
                } 
                catch (err) 
                {
                    echo "Failed to delete container ${CONTAINER_NAME}: ${err}"
                }
            }
            
            echo 'Cleaning Workspace'
            deleteDir()
         }
    }
       
}
